helium/hotspot-app

README.md
This repo is for the the next version of the app.
=> Add disclosure

README.md
=> add link to project board

src/features/moreTab/MoreNavigator.tsx, src/features/moreTab/more/MoreScreen.tsx, src/features/moreTab/moreTypes.tsx, src/features/moreTab/reveal/RevealWordsScreen.tsx, src/locales/en.ts, src/navigation/main/tabTypes.ts
=> Create reveal words screen.

android/app/src/main/java/com/helium/wallet/generated/BasePackageList.java, appcenter-pre-build.sh, ios/Podfile.lock, package.json
add a pre build script for app center to create a .env file
=> App Center Environment Variables

ios/Podfile.lock, package.json, yarn.lock
remove deprecated @react-native-community/picker
=> Fix Android Release Build

src/components/BackScreen.tsx, src/features/educationSetup/SetupHotspotEducationScreen.tsx, src/features/hotspots/setup/HotspotSetupBluetoothInfoScreen.tsx, src/features/hotspots/setup/HotspotSetupBluetoothSuccess.tsx, src/features/hotspots/setup/HotspotSetupConfirmLocationScreen.tsx, src/features/hotspots/setup/HotspotSetupLocationInfoScreen.tsx, src/features/hotspots/setup/HotspotSetupPickHotspotScreen.tsx, src/features/hotspots/setup/HotspotSetupPickWifiScreen.tsx, src/features/onboarding/accountCreatePassphrase/AccountCreatePassphraseScreen.tsx, src/features/onboarding/accountEnterPassphrase/AccountEnterPassphraseScreen.tsx, src/features/onboarding/accountEnterPassphrase/PhraseChip.tsx, src/utils/useHotspot.ts
=> Fix various android layout issues.

src/assets/images/chartIcon.svg, src/assets/images/receive.svg, src/assets/images/send.svg, src/assets/images/walletIcon.svg, src/features/wallet/root/ActivityCard/ActivityCard.tsx, src/features/wallet/root/BalanceCard/BalanceCard.tsx, src/features/wallet/root/BalanceCard/WalletButton.tsx, src/features/wallet/root/WalletIntroCarousel.tsx, src/features/wallet/root/WalletView.tsx, src/locales/en.ts, src/theme/theme.ts
Closes https://github.com/helium/hotspot-app/issues/108
https://user-images.githubusercontent.com/6345962/106684693-cd9e0480-657b-11eb-8823-aa4b5d642ba1.mov
=> Empty wallet view

src/features/hotspots/details/HotspotDetailChart.tsx, src/features/hotspots/details/HotspotDetails.tsx, src/locales/en.ts, src/store/hotspotDetails/hotspotDetailsSlice.ts, src/utils/appDataClient.ts
=> Challenge data for hotspot details

index.js, package.json, src/components/InputField.tsx, src/features/wallet/send/SendForm.tsx, src/features/wallet/send/SendView.tsx, src/locales/en.ts, src/utils/fees.ts, yarn.lock
=> Format and validate send amounts

src/features/moreTab/more/MoreScreen.tsx, src/locales/en.ts
=> Remove settings unit section.

src/store/connectedHotspot/connectedHotspotSlice.ts
=> Handle hotspot not yet being added to the chain.

src/App.tsx, src/features/moreTab/more/MoreScreen.tsx, src/features/wallet/root/ActivityCard/ActivityCard.tsx, src/features/wallet/root/ActivityCard/ActivityCardHeader.tsx, src/features/wallet/root/ActivityCard/ActivityCardListView.tsx, src/features/wallet/root/WalletScreen.tsx, src/features/wallet/root/WalletView.tsx, src/providers/LanguageProvider.tsx, src/utils/i18n.tsx
Fixes white flash when navigating away from activity tab. I believe the root cause was that there were overlapping calls to `LayoutAnimation.configureNext`
Closes #195
=> Remove animation pandemonium

src/features/hotspots/root/HotspotsView.tsx
resolves https://github.com/helium/hotspot-app/issues/203
=> Use tab button press to navigate back to hotspots list

src/App.tsx, src/components/ConfirmPinView.tsx, src/components/Keypad.tsx, src/features/lock/LockScreen.tsx, src/features/moreTab/more/useAuthIntervals.ts, src/features/onboarding/accountCreatePin/AccountCreatePinScreen.tsx
Closes #190 
User should no longer be asked for pin immediately after onboarding.
=> Fix a couple pin entry edge cases.

android/app/_BUCK, android/app/build.gradle, android/app/src/debug/java/com/helium/wallet/ReactNativeFlipper.java, android/app/src/main/AndroidManifest.xml, android/app/src/main/java/com/helium/wallet/MainActivity.java, android/app/src/main/java/com/helium/wallet/MainApplication.java, android/app/src/main/java/com/helium/wallet/generated/BasePackageList.java, ios/Helium.xcodeproj/project.pbxproj, ios/Helium/Helium.entitlements, ios/OneSignalNotificationServiceExtension/OneSignalNotificationServiceExtension.entitlements
Not sure when we should merge this, but here it is.
=> Remove v3 from package name.

ios/Helium.xcodeproj/project.pbxproj, ios/Podfile.lock
sentry-wizard duplicated a build phase and had the properties location wrong. This should fix both.
=> Remove duplicate build phase.

src/features/hotspots/setup/HotspotSetupConfirmLocationScreen.tsx
remove balance checks for free hotspot onboarding
closes #129
=> Free hotspot onboarding fix

src/features/hotspots/root/HotspotsView.tsx
ensure no location ui only shows for selected hotspot
=> no location fix

src/components/InputField.tsx
remove text field autocomplete on ios
=> remove text field autocomplete on ios

android/app/build.gradle
update android version code for release
=> update android version code

src/features/hotspots/details/TimelinePicker.tsx
=> Add minimum width to timeline picker.

src/locales/en.ts, src/store/connectedHotspot/connectedHotspotSlice.ts, src/utils/secureAccount.ts
Closes #249 
Husky reformatted some stuff on me.
=> Fix mnemonic not displaying after upgrading to v3.

android/app/src/main/AndroidManifest.xml
It was coming from expo-location https://docs.expo.io/versions/latest/sdk/location/
=> remove background location permission on Android

src/navigation/main/HomeNavigator.tsx
=> fix android getting stuck on blank screen after send

src/features/wallet/root/BalanceCard/BalanceCard.tsx
=> fixes account balances that end in 0

src/features/wallet/root/BalanceCard/BalanceCard.tsx, src/features/wallet/root/WalletScreen.tsx, src/features/wallet/root/WalletView.tsx, src/features/wallet/root/WalletViewContainer.tsx, src/features/wallet/root/walletLayout.tsx, src/features/wallet/root/walletTypes.ts, src/store/activity/activitySlice.ts, src/utils/animateTransition.ts
=> Fix no activity showing loading state indefinitely.

src/locales/ja.ts, src/locales/zh.ts
add missing JA
update bluetooth permissions in Chinese
=> add translations

src/features/wallet/root/ActivityDetails/HotspotTransaction.tsx, src/features/wallet/send/SendView.tsx, src/hooks/useSubmitTxn.ts, src/utils/transactions.ts
=> Fix hotspot transfer submission and detail view.

src/components/HotspotListItem.tsx, src/features/hotspots/root/HotspotsList.tsx, src/features/hotspots/root/HotspotsPicker.tsx, src/locales/en.ts, src/store/hotspots/hotspotsSlice.ts
- show "No Hotspots Offline" text for offline filter without offline hotspots
- ensure the list keeps the same filter if you leave the hotspots tab and come back
closes #253 
closes #262
=> update hotspots list for offline hotspots

android/app/src/main/java/com/helium/wallet/MainActivity.java
=> Enable Android screenshots

src/components/CircleLoader.tsx, src/components/TextInput.tsx, src/features/hotspots/details/HotspotDetails.tsx, src/features/hotspots/details/HotspotMoreMenuButton.tsx, src/features/hotspots/settings/WifiSettings.tsx, src/features/hotspots/settings/WifiSetup.tsx
Closes #310 
- Fixes not being able to change the wifi network when you're not configured to your configured network.
- Fixes some UX painpoints
=> Fix wifi forget and improve ux.

src/components/Address.tsx, src/components/BackButton.tsx, src/components/BackScreen.tsx, src/components/Button.tsx, src/components/ConfirmPinView.tsx, src/components/TextTransform.tsx, src/features/hotspots/details/HexBadge.tsx, src/features/hotspots/root/WelcomeOverview.tsx, src/features/hotspots/settings/HotspotSettings.tsx, src/features/hotspots/setup/HotspotSelectionCard.tsx, src/features/hotspots/setup/HotspotSelectionScreen.tsx, src/features/hotspots/setup/HotspotSetupBluetoothInfoScreen.tsx, src/features/hotspots/setup/HotspotSetupConfirmLocationScreen.tsx, src/features/hotspots/setup/HotspotSetupLocationInfoScreen.tsx, src/features/hotspots/setup/HotspotSetupPowerScreen.tsx, src/features/hotspots/setup/HotspotSetupWifiScreen.tsx, src/features/hotspots/transfers/HotspotTransfer.tsx, src/features/moreTab/more/MoreScreen.tsx, src/features/moreTab/reveal/RevealWordsScreen.tsx, src/features/onboarding/accountCreatePassphrase/AccountCreatePassphraseScreen.tsx, src/features/onboarding/accountCreatePin/AccountCreatePinScreen.tsx, src/features/onboarding/accountEnterPassphrase/AccountEnterPassphraseScreen.tsx, src/features/onboarding/accountEnterPassphrase/PhraseChip.tsx, src/features/onboarding/accountPassphraseWarning/AccountPassphraseWarningScreen.tsx, src/features/onboarding/importAccountConfirm/ImportAccountConfirmScreen.tsx, src/features/wallet/root/BalanceCard/BalanceCard.tsx, src/features/wallet/root/BalanceCard/CurrencyBadge.tsx, src/features/wallet/root/WalletIntroCarousel.tsx, src/features/wallet/root/WalletViewContainer.tsx
=> Apply font scaling factors to problematic text elements.

src/App.tsx, src/components/BarChart/WalletChart.tsx, src/utils/explorerClient.ts, src/utils/logger.ts, src/utils/stakingClient.ts, src/utils/walletClient.ts
=> remove noisy sentry logs and cleanup initial load

src/features/wallet/root/ActivityCard/ActivityCardHeader.tsx, src/features/wallet/root/ActivityCard/ActivityItem.tsx
=> ensure activity list translations update after language change

src/features/hotspots/settings/HotspotDiagnosticReport.tsx, src/features/hotspots/settings/HotspotDiagnosticsConnection.tsx, src/features/hotspots/settings/HotspotsDiagnosticOptions.tsx, src/features/hotspots/settings/ReassertLocation.tsx, src/features/hotspots/settings/ReassertLocationUpdate.tsx, src/features/hotspots/settings/WifiSettings.tsx, src/features/hotspots/settings/WifiSettingsContainer.tsx, src/features/hotspots/settings/WifiSetup.tsx, src/features/hotspots/setup/HotspotSetupConnectingScreen.tsx, src/features/hotspots/setup/HotspotSetupWifiConnectingScreen.tsx, src/features/hotspots/setup/HotspotSetupWifiScreen.tsx, src/features/hotspots/setup/HotspotTxnsProgressScreen.tsx, src/locales/en.ts, src/utils/bluetooth/useBluetooth.tsx, src/utils/useHotspot.ts
=> Show better errors when bluetooth ops fail.

ios/Helium/Info.plist
=> update the ios camera permission string

src/components/Word.tsx, src/features/hotspots/details/HotspotDetailChart.tsx, src/features/hotspots/setup/HotspotSetupBluetoothError.tsx, src/features/hotspots/setup/HotspotSetupBluetoothInfoScreen.tsx, src/features/hotspots/setup/HotspotSetupDiagnosticsScreen.tsx, src/features/hotspots/setup/HotspotSetupEducationScreen.tsx, src/features/hotspots/setup/HotspotSetupPickWifiScreen.tsx, src/features/onboarding/accountCreatePin/AccountCreatePinScreen.tsx, src/features/onboarding/accountImport/PassphraseAutocomplete.tsx, src/features/onboarding/accountImportComplete/AccountImportCompleteScreen.tsx, src/features/onboarding/importAccountConfirm/ImportAccountConfirmScreen.tsx, src/locales/en.ts, src/theme/theme.ts
closes #332 
Fixes various font scaling issues
=> Fix various font scaling issues.

src/features/hotspots/settings/ReassertAddressSearch.tsx, src/features/hotspots/setup/AddressSearchModal.tsx, src/locales/en.ts, src/theme/theme.ts
=> Use our TextInput for address search and remove extra padding in reassert

src/utils/logger.ts, src/utils/useHotspot.ts
Added device info to ble logging so we can more easily relate bugs to device types.
=> Add device info to crash logs for troubleshooting.

src/features/lock/LockScreen.tsx
=> fix text in alert when canceling pin

declarations.d.ts, ios/Podfile.lock, package.json, src/components/BarChart/WalletChart.tsx, src/components/HotspotListItem.tsx, src/features/hotspots/root/HotspotsList.tsx, src/features/hotspots/root/WelcomeOverview.tsx, src/features/wallet/root/ActivityCard/ActivityCardListView.tsx, src/features/wallet/root/ActivityCard/ActivityItem.tsx, src/features/wallet/root/ActivityDetails/ActivityDetails.tsx, src/features/wallet/root/ActivityDetails/ActivityRewardItem.tsx, src/features/wallet/root/ActivityDetails/ActivityRewardLine.tsx, src/features/wallet/root/BalanceCard/BalanceCard.tsx, src/features/wallet/root/WalletScreen.tsx, src/features/wallet/root/useActivityItem.tsx, src/utils/i18n.tsx, src/utils/useCurrency.ts, yarn.lock
Closes #359 
The Hermes js engine doesn't include `Intl`. So, decided to use native currency formatting which forced conversion to need to happen asynchronously.
=> Use native currency formatting

src/components/BarChart/WalletChart.tsx
Closes #339 
When selecting the 12M filter hide the bar labels
When 12M filter selected and a bar is being pressed show the date range in place of the filter.
=> Show date in place of range selectors when focusing on 30 day range.

src/locales/en.ts
=> update bluetooth pairing text

src/App.tsx, src/features/wallet/root/useActivityItem.tsx, src/store/helium/heliumDataSlice.ts
- Ensure splash screen doesnt get stuck waiting for the next block
- Update activity list times when block changes
=> splash screen and app load fix

src/features/hotspots/settings/WifiSettings.tsx, src/features/hotspots/setup/HotspotSetupPickWifiScreen.tsx, src/locales/en.ts
closes #388 
Adds the ability to re-scan wifi networks when onboarding and in hotspot settings.
=> wifi scan again

src/App.tsx, src/features/wallet/send/SendForm.tsx, src/features/wallet/send/SendView.tsx, src/locales/en.ts, src/utils/appDataClient.ts
closes #381 
check hotspot for POC activity in the last 1200 blocks (loaded from the chain var `transferHotspotStalePocBlocks`)
=> transfer hotspot stale activity check

src/features/moreTab/reveal/RevealWordsScreen.tsx, src/features/onboarding/accountCreatePassphrase/AccountCreatePassphraseScreen.tsx, src/features/onboarding/importAccountConfirm/ImportAccountConfirmScreen.tsx
=> Adjust fixed height on small phones, remove vertical padding.

src/App.tsx
Closes #414 
App will update "initial" data every time it comes into the foreground.
=> Update initial data when app comes into foreground.

src/features/hotspots/setup/HotspotSetupWifiScreen.tsx
=> Add password show toggle to wifi setup.

src/features/hotspots/settings/HotspotDiagnosticReport.tsx, src/features/hotspots/settings/sendReport.ts, src/utils/stakingClient.ts
closes #384 
sends diagnostic reports to the correct maker support emails:
Helium: support@helium.com
Nebra: support@nebra.com
Bobcat: support@bobcatminer.com
Syncrob.it: support@syncrob.it
=> compose diagnostic reports with hotspot makers email

package.json, src/App.tsx, src/components/StatusBanner.tsx, src/features/hotspots/root/HotspotsEmpty.tsx, src/features/wallet/root/BalanceCard/BalanceCard.tsx, src/locales/en.ts, src/store/account/accountSlice.ts, src/store/helium/StatusTypes.ts, src/store/helium/heliumStatusSlice.ts, src/store/hotspots/hotspotsSlice.ts, src/store/rootReducer.ts, src/utils/StatusClient.ts, yarn.lock
closes #434
- outage status banner
- failed state for wallet balance
- failed state for hotspots list
=> API Outage Status Banner

src/features/hotspots/checklist/HotspotChecklist.tsx, src/features/hotspots/checklist/HotspotChecklistItem.tsx
closes #450 
closes #459 
The checklist is still behind a feature flag that will need to be turned on to show up. You can mock it in the FeaturesSlice if you want to test.
=> only load checklist when expanded and fix cropped text

src/utils/polyfill.js
The app was crashing on launch for release builds only
=> fix crash on app launch

src/components/HotspotPairingList.tsx, src/features/hotspots/root/HotspotsTicker.tsx, src/features/hotspots/root/HotspotsView.tsx, src/locales/en.ts
Show settings cog when clicking on hotspot from map.
Nav to proper location when choosing location from search.
Change ticker easing to linear
Couple eslint/husky fixes
=> Hotspot Tab Fixes

src/components/HotspotListItem.tsx, src/features/hotspots/root/HotspotsList.tsx, src/features/hotspots/root/WelcomeOverview.tsx, src/features/hotspots/settings/HotspotSettings.tsx, src/locales/en.ts, src/locales/ja.ts, src/locales/ko.ts, src/locales/zh.ts, src/store/hotspots/hotspotsSlice.ts
Fix flash when moving between tabs
Show loading states when rewards not yet loaded
Update hotspot list item style
Fix null,null,null location name
Remove comma after greeting
Closes #409
=> Handle rewards loading states.

android/build.gradle
=> Set android target and compile sdk to 30.

src/features/wallet/root/walletLayout.tsx
=> Fix activity list animation points

src/features/notifications/NotificationList.tsx
=> sort notification groups by time

src/components/ConfirmPinView.tsx, src/components/Keypad.tsx, src/features/lock/LockScreen.tsx, src/features/moreTab/more/MoreScreen.tsx, src/features/onboarding/accountCreatePin/AccountCreatePinScreen.tsx, src/locales/en.ts
Add clearable option to keypad
Add signout option when clearable
Update signout alert prompt text
Closes #488
=> Pin Updates

src/components/HotspotConfigurationPicker.tsx
Updates the dBi value for the nebra indoor hotspot to 3dBi
=> Update dBi for nebra indoor hotspot

src/components/HotspotConfigurationPicker.tsx, src/utils/assertLocationUtils.tsx
On android if you didnt hit the done button on the keyboard for custom antenna details the information was not saved. This fixes that bug.
closes #507
=> ensure antenna gain and elevation updates are submit

src/features/hotspots/settings/HotspotDiagnosticReport.tsx, src/locales/en.ts
=> show unavailable for diagnostic defaults

src/features/hotspots/setup/HotspotSetupBluetoothError.tsx, src/features/hotspots/setup/HotspotSetupBluetoothInfoScreen.tsx, src/features/hotspots/setup/HotspotSetupDiagnosticsScreen.tsx, src/features/hotspots/setup/HotspotSetupEducationScreen.tsx, src/features/hotspots/setup/HotspotSetupPowerScreen.tsx, src/features/hotspots/setup/NotHotspotOwnerError.tsx, src/features/hotspots/setup/OwnedHotspotError.tsx
=> Center hotspot setup content vertically.

src/store/hotspotDetails/hotspotDetailsSlice.ts, src/utils/cacheUtils.ts
Here's some ideas on how to cleanup the code and make the cache more reusable.
=> Make cache reusable.

src/App.tsx, src/features/hotspots/root/HotspotsTicker.tsx, src/features/notifications/NotificationsScreen.tsx, src/locales/en.ts, src/navigation/main/MainTabNavigator.tsx, src/navigation/main/TabBarIcon.tsx, src/navigation/main/tabTypes.ts, src/store/account/accountSlice.ts, src/store/helium/heliumDataSlice.ts, src/store/notifications/notificationSlice.ts, src/store/rootReducer.ts
closes #442 
This makes it so that when you tap a push notification the app opens to the notifications screen after unlocking. This way when users get a notification and tap it they will see the new notification after opening the app.
=> open notification list when tapping push notifications

src/features/hotspots/details/HotspotDetails.tsx, src/features/hotspots/root/HotspotsView.tsx, src/store/hotspotDetails/hotspotDetailsSlice.ts, src/utils/cacheUtils.ts
closes #490 
With this change we cache the hotspot detail data for 5 minutes.
=> hotspot detail app level caching

src/features/notifications/NotificationsScreen.tsx, src/store/notifications/notificationSlice.ts
=> show loading indicator for initial notification fetch

declarations.d.ts, ios/Podfile.lock, package.json, src/App.tsx, src/components/Address.tsx, src/components/HeliumActionSheet.tsx, src/components/ShareHotspot.tsx, yarn.lock
=> fix action sheet scrolling on Android

src/features/hotspots/root/HotspotsPicker.tsx, src/features/hotspots/root/HotspotsScreen.tsx, src/features/hotspots/settings/HotspotSettings.tsx, src/features/hotspots/settings/discovery/DiscoveryMap.tsx, src/features/hotspots/settings/discovery/DiscoveryModeResults.tsx, src/features/hotspots/settings/discovery/DiscoveryModeRoot.tsx, src/locales/en.ts, src/store/discovery/discoverySlice.ts, src/utils/useGetLocation.ts, src/utils/usePermissionManager.ts
=> Use phone location when disco mode on unasserted hotspot.

ios/Podfile.lock, src/components/HeliumActionSheet.tsx, src/components/HotspotConfigurationPicker.tsx, src/components/ShareHotspot.tsx, src/constants/antennas.ts, src/features/hotspots/root/HotspotsView.tsx, src/providers/AppLinkProvider.tsx, src/store/hotspots/hotspotOnboardingSlice.ts
Update app link path format
Fix `No Asserted Location flashing` when using App Link
New format is `helium://hotspot/{hotspot_address}`
=> App Link Fixes and Updates

ios/Podfile.lock, package.json, src/features/hotspots/settings/updateHotspot/UpdateHotspotConfig.tsx, src/features/hotspots/setup/HotspotTxnsProgressScreen.tsx, src/utils/assertLocationUtils.tsx, yarn.lock
=> use speculative nonce for hotspot location assert transactions

android/app/build.gradle, ios/Helium.xcodeproj/project.pbxproj, package.json
Reverts helium/hotspot-app#561
=> bump 3.2.0

src/features/hotspots/settings/discovery/DiscoveryMap.tsx, src/features/hotspots/settings/discovery/DiscoveryModeResults.tsx, src/utils/mapUtils.ts
Fix android crash when using hotspot physical location
Zoom to bounds when using hotspot physical location
closes #562 
closes #563
=> Disco Map Fixes

src/features/hotspots/settings/discovery/DiscoveryMap.tsx, src/features/hotspots/settings/discovery/DiscoveryModeResults.tsx, src/features/hotspots/settings/discovery/DiscoveryModeResultsCard.tsx, src/locales/en.ts
Cleanout some unused code
Enable disco map zoom with max level 12
Change 'Physical Location' to 'Temporary Location'
Fix transparency issue on android disco results card
=> Discovery Improvements

android/app/build.gradle, ios/Helium.xcodeproj/project.pbxproj, package.json, src/features/hotspots/settings/HotspotDiagnosticsConnection.tsx, src/features/hotspots/setup/AntennaSetupScreen.tsx
=> Resolves newly reported app crashes

src/features/hotspots/transfers/HotspotTransfer.tsx, src/features/hotspots/transfers/TransferBanner.tsx, src/features/notifications/NotificationShow.tsx, src/features/wallet/send/SendScreen.tsx, src/features/wallet/send/SendView.tsx, src/features/wallet/send/sendTypes.ts, src/navigation/main/tabTypes.ts
=> fix transfer flow from notification

src/features/hotspots/settings/discovery/DiscoveryMap.tsx
Closes #583 
For some reason on android, the disco map is hidden after a background/foreground of the app. It seems to be a bug with the Mapbox lib, but for now, a simple fix is to unmount/remount when visibility changes.
=> Fix blank disco map after background on android

src/features/hotspots/settings/discovery/DiscoveryModeBegin.tsx, src/locales/en.ts
=> Add session length to disco header.

src/features/hotspots/settings/HotspotSettings.tsx, src/features/hotspots/settings/updateHotspot/UpdateHotspotConfig.tsx, src/locales/en.ts
=> handle consecutive pending assert txns

package.json, src/App.tsx, src/features/hotspots/settings/discovery/DiscoveryMap.tsx, src/store/user/appSlice.ts, src/utils/useGetLocation.ts, src/utils/useVisible.ts, yarn.lock
There were some edge cases where the `useVisible` hook was wrong on Android. Hoping this will clear them up.
=> Move appstate from slice and to appstate lib hook

src/features/hotspots/settings/discovery/DiscoveryModeRoot.tsx, src/features/hotspots/settings/discovery/useDiscoveryPoll.ts, src/store/discovery/discoverySlice.ts, src/store/discovery/discoveryTypes.ts
=> Fix disco timer when app put in background.

src/features/wallet/send/SendDetailsForm.tsx, src/features/wallet/send/SendForm.tsx, src/utils/transactions.ts
=> fix payments with amounts larger than 4 digits

src/components/SearchInput.tsx, src/features/hotspots/setup/HotspotSelectionScreen.tsx, src/theme/theme.ts
=> Add search field to hotspot onboarding selection screen.

src/components/InputField.tsx, src/components/LockedField.tsx, src/features/wallet/root/ActivityDetails/Payment.tsx, src/features/wallet/root/ActivityDetails/PaymentItem.tsx, src/features/wallet/send/SendDetailsForm.tsx, src/features/wallet/send/SendForm.tsx
=> fix send forum corners

src/features/wallet/root/useActivityItem.tsx
=> Fix DC unit not showing for some pending payments.

src/constants/articles.ts, src/features/hotspots/details/HexBadge.tsx, src/features/moreTab/more/MoreScreen.tsx, src/locales/en.ts
=> Show prompt when clicking reward scale pill

src/components/NetworkCoverage.tsx, src/components/NetworkPointCoverage.tsx, src/features/map/MapFilterModal.tsx
- fix map filter ui issues on Android
- fix network map zoomed out view on Android
closes #658
=> android network map fixes

src/components/ContentPill.tsx, src/features/hotspots/settings/discovery/DiscoveryModeResultsCard.tsx
=> Hide content pill when one item. Fix auto-scroll.

.github/ISSUE_TEMPLATE/bug_report.md, ios/Podfile.lock, src/features/map/MapFilterModal.tsx, src/locales/en.ts
=> Fix map filter layout when font scaled up.

src/utils/hotspotUtils.ts
=> Update isRelay logic to check for the existence of any ip4

src/makers/sensecap/index.ts
We have modified the support email for Sensecap.
=> modify the support email

src/makers/sensecap/hotspots.ts
We have modified the support email for Sensecap.
=>  Modified the support email for Sensecap.

package.json, src/components/Coverage.tsx, src/components/HotspotsCoverage.tsx, src/components/Map.tsx, src/features/hotspots/root/HotspotsView.tsx, src/store/discovery/discoveryTypes.ts, yarn.lock
use the new location hex property for hotspot h3 locations
=> hotspot location hex

ios/Podfile.lock, package.json, src/features/hotspots/settings/discovery/useShareDiscovery.tsx, yarn.lock
=> Fix disco email rendering as html on ios.

src/makers/syncrobit/antennas.ts
=> Update antenna gain to 3dbi

src/features/security/SecurityScreen.tsx, src/makers/rak/hotspots.ts, src/makers/syncrobit/hotspots.ts
- fix splash screen security screen
- fix rak and synco onboarding type
=> release bugs

src/features/hotspots/details/HotspotDetails.tsx
=> Fix hotspot name transition on android.

src/features/hotspots/settings/discovery/useShareDiscovery.tsx
=> Fix android disco share text formatting.

src/utils/parseMarkup.tsx
replace would only get the first one, which actually fixed the bug but we should replace all of them
=> ensure all invalid quote occurrences get replaced

src/features/wallet/send/SendDetailsForm.tsx, src/utils/transactions.ts
=> Fix incorrect byte size calc failing memo validation

src/features/hotspots/setup/OnboardingErrorScreen.tsx, src/locales/en.ts, src/utils/stakingClient.ts, src/utils/useHotspot.ts
=> Handle onboarding service unavailable when onboarding hotspot.

src/makers/__example__/hotspots.ts
=> Add qr strings example to maker files.

src/features/hotspots/root/HotspotsEmpty.tsx, src/features/hotspots/root/HotspotsList.tsx, src/features/hotspots/root/HotspotsScreen.tsx, src/features/hotspots/root/HotspotsView.tsx, src/locales/en.ts
https://www.figma.com/file/x07XtWRI573FfO8duPMIEz/3.4.0?node-id=300%3A2
=> Update hotspots empty state.

src/features/hotspots/settings/ReassertLocation.tsx, src/features/hotspots/settings/ReassertLocationUpdate.tsx, src/locales/en.ts
=> check for no location change when updating hotspot location

src/features/notifications/NotificationItem.tsx, src/features/notifications/NotificationShow.tsx
- increase list item font size
- move notification details back to bottom
=> update notification list font size

src/features/hotspots/root/ShortcutNav.tsx, src/features/wallet/root/WalletAddress.tsx, src/features/wallet/root/WalletView.tsx, src/navigation/main/MainTabNavigator.tsx, src/navigation/main/TabBarIcon.tsx, src/theme/theme.ts
Fix Shortcut Nav hotspot sorting
Show loading indicator on wallet screen
Closes #769
=> Update Shortcut Nav and tab bar icon colors

src/features/hotspots/settings/discovery/DiscoveryModeRoot.tsx, src/locales/en.ts, src/store/discovery/discoverySlice.ts
=> Warn users of disco mode instability.

package.json, src/components/HotspotListItem.tsx, src/features/hotspots/details/HotspotDetails.tsx, src/features/hotspots/root/HotspotsList.tsx, src/features/hotspots/settings/discovery/DiscoveryModeRoot.tsx, src/store/hotspots/hotspotsSlice.ts, src/utils/hotspotUtils.ts, yarn.lock
Change block sync buffer to 1,500.
Use hotspot.status.timestamp to determine currently synced block.
=> Change block sync buffer to 1,500.

src/components/HotspotListItem.tsx, src/features/hotspots/details/HotspotDetailChart.tsx, src/features/hotspots/details/HotspotDetails.tsx, src/features/hotspots/details/StatusBadge.tsx, src/features/hotspots/details/TimelinePicker.tsx, src/features/hotspots/root/HotspotSearch.tsx, src/features/hotspots/root/HotspotsList.tsx, src/features/hotspots/root/HotspotsView.tsx, src/features/hotspots/root/ShortcutNav.tsx, src/store/hotspots/hotspotsSlice.ts
Closes #784 
Render all ShortcutNav pills at once to avoid snap jank.
Only dispatch search if term has changed.
Remove fetch and display of sync status for hotspot list items.
Cleanup HotspotDetailChart layout.
Only load data when bottom sheet is expanded.
Fix offset for last item in shortcutnav.
=> Fix the damn lag

src/features/hotspots/checklist/HotspotChecklist.tsx, src/features/hotspots/details/HotspotStatusBanner.tsx, src/locales/en.ts, src/store/hotspots/hotspotsSlice.ts, src/utils/hotspotUtils.ts
=> Use fetched hotspot block height in checklist and status banner.

src/features/wallet/send/SendView.tsx, src/providers/appLinkTypes.ts
=> Allow qr payment amount to be a number or string.

src/features/wallet/root/WalletView.tsx
=> Show balance while activity is still loading.

src/features/hotspots/settings/HotspotSettings.tsx, src/store/features/featuresSlice.ts
=> Fix modal not extending under status bar.

src/makers/nebra/hotspots.ts
fix default antenna for nebra outdoor miner
Signed-off-by: Aaron Shaw <shawaj@gmail.com>
=> antennas: fix default for nebra outdoor

src/makers/nebra/hotspots.ts
updates informational text about bluetooth and LED functionality for nebra miners
Closes: #810 
Signed-off-by: Aaron Shaw <shawaj@gmail.com>
=> onboarding: update nebra onboarding information

src/features/hotspots/details/StatusBadge.tsx, src/features/hotspots/useHotspotSync.tsx, src/locales/en.ts
=> Handle null hotspot status timestamp.

src/features/hotspots/checklist/HotspotChecklistItem.tsx
=> Fix complete and pending simultaneously showing in witness list.

src/store/user/appSlice.ts, src/utils/logger.ts, src/utils/secureAccount.ts
users addresses were not getting tagged in sentry when the user was restored
=> ensure restored user tags get set in sentry

package.json, src/features/hotspots/useHotspotSync.tsx, src/utils/appDataClient.ts, src/utils/fees.ts, yarn.lock
move status height call to use helium-js
=> update status height call

ios/Helium.xcodeproj/project.pbxproj, package.json, src/components/Map.tsx, src/features/hotspots/settings/HotspotDiagnosticReport.tsx, src/features/hotspots/settings/sendReport.ts, src/locales/en.ts
- Fix crash when updating hotspot location for hotspots that skipped assert during onboarding
- Add more detail to the diagnostic report email
closes #878 
closes #877
=> Assert crash and diagnostic report update

src/features/hotspots/settings/DiagnosticLineItem.tsx, src/features/hotspots/settings/HotspotDiagnosticReport.tsx, src/features/hotspots/settings/discovery/useShareDiscovery.tsx, src/features/hotspots/settings/sendReport.ts, src/locales/en.ts, src/utils/bluetooth/bluetoothDataParser.ts, src/utils/sendMail.ts
=> Add disk status to diagnostic report and fix line break.

src/components/Map.tsx, src/utils/mapUtils.ts
=> check to make sure map coords are a number

src/features/onboarding/welcome/WelcomeScreen.tsx
This adds the `.env` variable `WORDS`. The var needs to contain your 12 comma-separated words which will allow you to skip manual entry.
=> Enable passphrase entry via env var.

ios/Podfile.lock, src/features/hotspots/settings/discovery/DiscoveryModeRoot.tsx, src/locales/en.ts, src/store/discovery/discoverySlice.ts
=> Remove disco instability warning.

src/components/Map.tsx, src/features/hotspots/details/HotspotDetails.tsx, src/features/hotspots/root/HotspotsView.tsx
=> Handle misasserted locations when showing hotspot witnesses.

src/features/hotspots/root/HotspotsPicker.tsx, src/locales/en.ts, src/store/hotspots/hotspotsSlice.ts
=> Add unasserted filter when fleet mode enabled.

src/features/hotspots/root/HotspotsTicker.tsx, src/features/onboarding/welcome/WelcomeScreen.tsx
Some lint issues were introduced by #833
=> fix lint errors

src/components/InputField.tsx, src/features/wallet/send/SendDetailsForm.tsx, src/features/wallet/send/SendForm.tsx, src/locales/en.ts
=> check if payment address is a hotspot or validator address

src/features/hotspots/root/ShortcutNav.tsx
=> scroll to explore tab if selecting an unowned or followed hotspot

src/components/HeliumActionSheet.tsx, src/components/HeliumActionSheetItem.tsx, src/features/moreTab/more/MoreListItem.tsx, src/features/moreTab/more/MoreScreen.tsx, src/locales/en.ts, src/store/account/accountSlice.ts, src/utils/useCurrency.ts
=> Create currency type selector.

package.json, yarn.lock
It needed a fix in react-native-mail for target SDK 30
https://github.com/chirag04/react-native-mail/pull/175
closes #1044
=> fix diagnostic email on android

ios/Podfile.lock, package.json, src/features/hotspots/root/ShortcutNav.tsx, src/utils/animateTransition.ts, yarn.lock
resolves a couple top crashes on Android
closes #1055
=> Fix Android top crashes

src/makers/syncrobit/hotspots.ts
@matthewcarlreetz My fork somehow messed up, submitting this new PR and closing the old one
=> Syncrobit QR Code Implementation

src/features/hotspots/setup/HotspotSetupExternalScreen.tsx, src/features/wallet/root/ActivityCard/ActivityCardListView.tsx, src/features/wallet/root/WalletHeader.tsx, src/features/wallet/scan/ScanView.tsx, src/providers/AppLinkProvider.tsx
=> fix qr scan on second attempt

android/app/src/main/res/values/strings.xml, src/features/hotspots/details/HotspotDetails.tsx
- android splash screen set to cover mode
- fix transparent background on hotspot detail card
=> minor ui fixes

src/store/rootReducer.ts, src/store/store.ts
remove cache for a couple reducers as some users are reporting problems with stale hotspot data
=> cache updates

src/components/HotspotConfigurationPicker.tsx
- default to custom antenna when clicking gain without an antenna selected
- make sure keyboard "done" button dismisses keyboard properly
=> hotspot config fixes

src/components/Address.tsx, src/features/wallet/root/ActivityDetails/ActivityDetails.tsx, src/features/wallet/root/ActivityDetails/ActivityDetailsHeader.tsx, src/features/wallet/root/useActivityItem.tsx, src/locales/en.ts, src/store/rootReducer.ts
- dont cache selected activity item
- show transaction hash in activity details and allow copy / view in explorer
closes #1128 
closes #1130
=> activity details updates

src/features/hotspots/settings/updateHotspot/UpdateHotspotConfig.tsx, src/features/hotspots/transfers/HotspotTransfer.tsx
Hopefully fixes the disappearing hotspots settings modal.
closes #1083
=> add min height to hotspot settings modals

src/features/wallet/root/ActivityDetails/Payment.tsx, src/features/wallet/scan/ScanView.tsx
Expo recommends setting the onBarCodeScanned to undefined after a scanning
https://github.com/expo/expo/issues/345
=> make sure scan view stops scanning after finding a qr

src/features/hotspots/settings/HotspotSettings.tsx, src/features/hotspots/settings/discovery/DiscoveryModeBegin.tsx, src/features/hotspots/settings/discovery/DiscoveryModeResults.tsx, src/features/hotspots/settings/updateHotspot/UpdateHotspotConfig.tsx, src/features/hotspots/transfers/HotspotTransfer.tsx, src/features/moreTab/more/MoreScreen.tsx, src/locales/en.ts, src/store/account/accountSlice.ts, src/utils/animateTransition.ts
- remove hotspot settings spring animation
- remove blur box for hotspot settings
- simplify hotspot settings ui
- remove disable animations setting (was just for testing and didnt help)
=> Another attempt to fix hotspot settings black screen

src/features/hotspots/settings/HotspotSettings.tsx, src/features/hotspots/settings/discovery/DiscoveryModeBegin.tsx, src/features/hotspots/settings/discovery/DiscoveryModeResults.tsx, src/features/hotspots/settings/updateHotspot/UpdateHotspotConfig.tsx, src/features/hotspots/transfers/HotspotTransfer.tsx, src/features/moreTab/more/MoreScreen.tsx, src/locales/en.ts, src/store/account/accountSlice.ts, src/utils/animateTransition.ts
This did not resolve the problem. I have another PR coming to fix it.
=> Revert "Another attempt to fix hotspot settings black screen"

src/features/wallet/send/SendDetailsForm.tsx
=> validate address after qr scan

src/features/hotspots/settings/HotspotDiagnosticReport.tsx, src/locales/en.ts
=> add block height to the diagnostic report

src/features/hotspots/settings/updateHotspot/UpdateHotspotConfig.tsx
=> ensure hotspot details are up to date when submitting assert txns

src/makers/merryIoT/antennas.ts, src/makers/merryIoT/hotspots.ts
Update antenna value and structure name.
=> Update antenna gain value and rename the structure to MERRYIOT

src/features/hotspots/details/HotspotDetailChart.tsx, src/features/hotspots/details/TimelinePicker.tsx, src/locales/en.ts, src/locales/ja.ts, src/locales/ko.ts, src/locales/zh.ts, src/store/features/featuresSlice.ts, src/store/rewards/rewardsSlice.ts
=> Show ytd hotspot earnings.

src/makers/hntenna/antennas.ts, src/makers/index.ts
=> remove hntenna

ios/Podfile.lock, src/features/hotspots/transfers/HotspotTransfer.tsx, src/features/wallet/root/ActivityDetails/ActivityDetails.tsx, src/features/wallet/root/ActivityDetails/ActivityDetailsHeader.tsx, src/features/wallet/root/ActivityDetails/HotspotTransaction.tsx, src/features/wallet/send/SendView.tsx
ensure transfer submit button cant be spammed, add a check for existing pending transfer, and fix some spacing
=> Transfer V2 Fixes

src/features/onboarding/accountImport/PassphraseAutocomplete.tsx, src/features/wallet/send/SendDetailsForm.tsx
- validate that transfer buyer address isn't a hotspot address
- dont allow spaces when inputting seed phrase
=> transfer fixes

src/constants/articles.ts, src/features/hotspots/details/DenylistBadge.tsx, src/features/hotspots/details/HotspotDetails.tsx, src/features/hotspots/root/HotspotsView.tsx, src/locales/en.ts, src/store/hotspotDetails/hotspotDetailsSlice.ts, src/utils/appDataClient.ts
=> identify denylist hotspots

src/components/HotspotListItem.tsx, src/components/Map.tsx, src/features/hotspots/root/HotspotsView.tsx, src/locales/en.ts
=> Show location updating when hotspot has pending assert.

src/features/hotspots/setup/HotspotSetupSelectionScreen.tsx, src/locales/en.ts, src/makers/bobcat/index.ts, src/makers/index.ts, src/makers/makerType.ts
=> During onboarding direct users to maker app when exists.

src/features/hotspots/setup/HotspotSetupSelectionScreen.tsx, src/locales/en.ts, src/makers/bobcat/index.ts, src/makers/makerType.ts, src/utils/useAlert.ts
Allows maker to set whether or not we will force users to redirect to their apps
=> add forceRedirect property to the maker config

src/utils/appDataClient.ts
=> add state_channel_close_v1 to transfer activity check

src/features/txnDelegatation/SignHotspot.tsx, src/locales/en.ts
=> Fix transfer error copy and sign hotspot UI on small devices

ios/Podfile.lock, src/features/wallet/root/useActivityItem.tsx
Handles when token type is a byte array in activity list
=> Fix crash when tapping on payment activity.

src/features/hotspots/root/WelcomeOverview.tsx, src/features/hotspots/settings/updateHotspot/UpdateHotspotConfig.tsx, src/features/hotspots/transfers/HotspotTransfer.tsx, src/locales/en.ts, src/navigation/main/MainTabNavigator.tsx
- removes the detail alert
- still showing an alert to export key
=> update migration alert

ios/Helium.xcodeproj/project.pbxproj, package.json, src/components/SentinelScreen.tsx, src/features/moreTab/reveal/RevealPrivateKeyScreen.tsx, src/locales/en.ts, yarn.lock
- adds password to export key flow
- bump version to 4.3.1
=> export updates

android/app/src/main/AndroidManifest.xml, ios/Helium.xcodeproj/project.pbxproj, package.json, src/locales/en.ts, src/utils/bluetooth/useBluetooth.tsx
Fixes for Android 12 permissions 
```
<uses-permission android:name="android.permission.BLUETOOTH_SCAN" />
<uses-permission android:name="android.permission.BLUETOOTH_CONNECT" />
```
=> fixes for ble android permissions

ios/Helium.xcodeproj/project.pbxproj, package.json, src/navigation/main/MainTabNavigator.tsx, src/navigation/main/TabBarIcon.tsx, src/utils/timeUtils.ts
- show sentinel and solana alert once a week
- bump version to 4.3.3
=> update sentinel time
