android/app/_BUCK, android/app/build.gradle, android/app/src/debug/java/com/helium/wallet/ReactNativeFlipper.java, android/app/src/main/AndroidManifest.xml, android/app/src/main/java/com/helium/wallet/MainActivity.java, android/app/src/main/java/com/helium/wallet/MainApplication.java, android/app/src/main/java/com/helium/wallet/generated/BasePackageList.java, ios/Helium.xcodeproj/project.pbxproj, ios/Helium/Helium.entitlements, ios/OneSignalNotificationServiceExtension/OneSignalNotificationServiceExtension.entitlements, ios/Podfile.lock
Changes app id as mentioned in https://github.com/helium/hotspot-app/issues/32 so that we can set up a release train on appcenter that won't overwrite the current app, for now.
=> new identifier for testing

src/features/moreTab/more/MoreScreen.tsx, src/features/wallet/scan/ScanView.tsx, src/features/wallet/send/SendForm.tsx, src/features/wallet/send/SendView.tsx, src/locales/en.ts, src/utils/explorerClient.ts
[ENS](https://ens.domains/) supports HNT, this allows a valid ENS address to be used to send HNT.
Some unrelated code style changes also seem to have gotten picked up by my husky hook.
=> Add support for ENS addresses

src/features/hotspots/details/HotspotDetailChart.tsx, src/features/hotspots/details/HotspotDetails.tsx, src/theme/theme.ts
resolves https://github.com/helium/hotspot-app/issues/121
I broke out this out to a separate issue because it's nontrivial: https://github.com/helium/hotspot-app/issues/224
Showing other hotspots on the map is also already its own issue
=> Hotspot page design tweaks

src/features/security/SecurityScreen.tsx
Closes #234
Security screen wasn't full screen on the iPhone 12 Pro Max. Updated the layout to handle it differently.
=> Make security screen full screen.

src/components/Dropdown.tsx
resolves #272 
Now looks like:
=> fix dropdown caret spacing

src/App.tsx, src/components/BarChart/WalletChart.tsx, src/store/account/accountSlice.ts, src/utils/logger.ts
Adds chart data to the data that gets fetched on initial load and when new blocks come in. I noticed that the chart data wasn't updating when I was testing pending transactions. This should make it consistent with the timing of the other data we fetch.
=> fetch account chart data when new blocks come in

src/features/lock/LockScreen.tsx, src/features/moreTab/more/MoreListItem.tsx, src/features/wallet/root/WalletViewContainer.tsx, src/features/wallet/scan/ScanView.tsx, src/features/wallet/send/SendNavigator.tsx, src/navigation/main/tabTypes.ts
closes #302 
- Fixes require pin for payments
- Require pin when navigating to send screen from wallet
- Require pin when navigating to send from payment QR 
- Updates the Android toggle colors in settings to match iOS
=> pin for payment

src/components/EmojiBlip.tsx, src/features/hotspots/setup/HotspotSetupConfirmLocationScreen.tsx, src/features/hotspots/setup/HotspotSetupConnectingScreen.tsx, src/features/hotspots/setup/HotspotSetupNavigator.tsx, src/features/hotspots/setup/OnboardingErrorScreen.tsx, src/features/hotspots/setup/hotspotSetupTypes.tsx, src/locales/en.ts, src/utils/useHotspot.ts
at one point we were throwing an alert error when onboarding record couldn't be found. The logic to trigger this alert changed and it was no longer getting triggered, leading the user to get further along in the setup than they should have. This adds a proper screen for onboarding error, and navigates to it when there is no onboarding record.
resolves: #307
=> add onboarding error screen to hotspot setup flow

src/components/Map.tsx, src/features/hotspots/details/HotspotDetails.tsx, src/features/hotspots/root/HotspotsView.tsx, src/utils/logger.ts
closes #251 
- Open details in expanded mode by default
- Swiping the list down still opens the details minimized
- Fixes reward scaling now showing on network hotspots
- Improves animation when jumping between hotspots
https://user-images.githubusercontent.com/6345962/109373875-60258100-7866-11eb-8a26-ce67a65c8761.mov
=> open hotspot details expanded & improve map navigation

src/components/BackButton.tsx, src/components/Map.tsx, src/features/hotspots/details/HotspotDetails.tsx, src/features/hotspots/root/HotspotsEmpty.tsx, src/features/hotspots/root/HotspotsScreen.tsx, src/features/hotspots/root/HotspotsView.tsx, src/locales/en.ts, src/utils/appDataClient.ts
closes #337 
closes #314 
closes #184 
Allows users without hotspots in their to view hotspots around them. This will be more beneficial when we also add the ability to favorite hotspot.
This also makes some changes to the map so that you retain your selected hotspot if you go back and forth. So if I select one and go back to the list and then swipe the list down the map no longer resets. It will reset when you hit "My Hotspots", but I did that by design and we could also keep the previous state if we wanted instead.
Currently the flow works as so
1. If you open the app and have not enabled location permission you see the current hotspot empty screen (no bottom sheet or map)
2. When you enable location you jump into the map at your location. If you permanently enable location you will now …
=> enable accounts without hotspots to view hotspots around them

package.json, src/features/hotspots/settings/HotspotDiagnosticReport.tsx, src/features/hotspots/settings/sendReport.ts, src/locales/en.ts, src/store/connectedHotspot/connectedHotspotSlice.ts, src/utils/useHotspot.ts, yarn.lock
Removes the old hotspot type that was calculated from onboarding address formatting which no longer works.
Replaces it with the onboarding maker name. In the case there is no maker name (DYI or something goes wrong) it will show 'unknown' in diagnostics.
=> remove legacy hotspot type

ios/Helium/Info.plist, ios/Podfile.lock, src/navigation/NavigationRoot.tsx
closes #370 
I think state of the map / some of the components remains on logout and log back in right away since they are in the same stack, components may not unmount. 
Coco ran into this problem but I couldn't get it to happen on my device. I moved each stack to its own navigator to see if maybe that helps.
=> update location permission string and fix state not clearing on logout

src/App.tsx, src/store/user/appSlice.ts, src/utils/secureAccount.ts
We were missing the onesignal tags for account data.
- I think this would lead to notifications not working on devices that were never on the V2 app 
- Deleting the tag should resolve the issue of notifications being sent to devices that have logged out of an account
closes https://github.com/helium/wallet-api/issues/22
=> add onesignal account tags

appcenter-pre-build.sh
After the update to reanimated v2 we no longer need the patch and I removed it but forgot to remove the patch install from the app center build script.
=> remove patch install from build script

src/components/InputField.tsx, src/features/hotspots/settings/HotspotSettings.tsx, src/features/wallet/send/SendForm.tsx
- The transfer modal animation was causing the dialog to disappear. Keeping a UI element above it, the title causes it to remain in view
- Fixes the transfer send form amount text clipped on Android
=> Fix transfer modal on android

ios/Podfile.lock, src/features/notifications/NotificationItem.tsx, src/hooks/useSubmitTxn.ts, src/utils/appDataClient.ts, src/utils/walletClient.ts
This submits all transactions through wallet-api rather than to the api directly.
Note that we'll want to wait to merge this until the wallet api change has been deployed.
It also changes the notification list item to use the notification icon url that is supplied with each notification. I updated all of the icon url references in wallet api to use the new styles going forward.
=> Submit transactions through wallet-api

src/features/hotspots/settings/HotspotDiagnosticReport.tsx
Fixes https://github.com/helium/hotspot-app/issues/424
If a hotspot does not have any challenges, export the "last challenge" as "never" in diagnostic reports instead of start of unix time (1970-01-01).
=> Fix "Last Challenge" date shown as beginning of Unix time instead of "never"

package.json, src/features/hotspots/root/hotspotTypes.tsx, src/features/wallet/root/ActivityDetails/Rewards.tsx, src/features/wallet/root/useActivityItem.tsx, src/features/wallet/root/walletTypes.ts, yarn.lock
adds support for `rewards_v2` transactions which the API should display the same as `rewards_v1`. 
depends on: https://github.com/helium/helium-js/pull/152
=> add support for rewards_v2

src/components/BubbleSelect.tsx
Looks like the bottom sheet provided components only work for vertical scroll, so we need to use the gesture handler ones for horizontal.
https://github.com/gorhom/react-native-bottom-sheet/issues/46#issuecomment-708386676
=> fix hotspot filter scrolling issues

android/build.gradle
Reverts helium/hotspot-app#482
This was causing crashes on some Android 11 devices.
=> Revert "Set android target and compile sdk to 30."

src/locales/en.ts
=> Fix Paring->Pairing typo

src/features/hotspots/setup/HotspotSelectionScreen.tsx, src/store/hotspots/hotspotOnboardingSlice.ts
This fixes a bug when onboarding two hotspots in a row and setting location for the first but skipping location for the second.
closes #522
=> clear onboarding state when starting hotspot setup

android/gradle.properties, ios/Helium.xcodeproj/project.pbxproj, ios/Podfile, ios/Podfile.lock, package.json, yarn.lock
Workarounds for some appcenter build issues
Android: https://github.com/microsoft/appcenter/issues/1738
iOS (Mapbox): https://github.com/react-native-mapbox-gl/maps
If we want to reenable flipper this might work too https://github.com/facebook/react-native/issues/31179 but I think lets just leave it disabled for now.
=> fix react native 64 app center issues

src/features/hotspots/settings/HotspotDiagnosticsConnection.tsx, src/locales/en.ts
closes #593 
Hotspots are failing to connect with the ongoing hotspot / mine issues and once those are resolved this error should clear up.
I am updating the error message to better fit the case:
title: "Hotspot Pairing Failed"
message: "Hotspot Miner is unable to respond to requests. Please reboot the Hotspot and try again later."
=> update connect failed dialog

ios/Podfile.lock, src/components/H3Grid.tsx, src/components/Map.tsx
The map was starting out zoomed and trying to calculate bounds, we need to prevent calculations when zoomLevel is null
closes #671
=> fix assert map crashing

src/utils/parseMarkup.tsx
Notifications were sometimes using `“` vs `"` and it throws off the parsing for markup.
closes #704
=> ensure notification markup uses proper quotes

src/components/ContentPill.tsx
When tapping through witnesses content pill would crash due to the animateTransition call.
closes #696
=> fix content pill crash on Android

src/App.tsx, src/components/StatusBanner.tsx, src/locales/en.ts, src/store/discovery/discoverySlice.ts, src/store/helium/heliumStatusSlice.ts, src/store/hotspots/hotspotsSlice.ts, src/utils/StatusClient.ts, src/utils/walletClient.ts
Remove ui concerns from slice to status component.
Only show relevant incidents.
Persist incidents. Only show ones we haven't before.
Remove status fetching and data.
Localize banner description.
Closes #735
=> Add conditions to reduce status banner display frequency

ios/Podfile.lock, package.json, yarn.lock
This was breaking the build on Android. I think we will need to update all the expo libraries as well as the current react native version to get everything working. 
For now we can safely revert.
=> revert unimodules back to 0.11.0

src/providers/AppLinkProvider.tsx
Currently, the QR scanning feature in "Send" supports multiple payments per-transaction if the QR code data is formatted exactly as follows:
```typescript
{
type: string
payees: {
[payeeAddress]: { amount: string, memo?: string },
[payeeAddress]: { amount: string, memo?: string },
...
}
}
```
However, it does not fully support the following
```typescript
{
type: string
payees: {
[payeeAddress]: amount,
[payeeAddress]: amount,
...
}
}
```
In the case above, only the address is pre-filled in the "Send" view (amount field remains blank).
This PR adds back support for the latter format which is helpful when submitting a large number of payments (the more payments you can squeeze into a QR code the better, so if you don't need memos then the latter format is more concise). This also updates …
=> Fix support for QR-scanned multi-payments

src/features/hotspots/details/HotspotDetails.tsx
Fixes the following scenario...
Open hotspot from list
Swipe up to see earnings
Earnings load
Tap home
Select different hotspot
Swipe up to see earnings
Infinite load
=> Fix hotspot details not loading.

src/features/hotspots/root/HotspotsView.tsx
=> Fix infinite loop when deep linking to hotspot.

src/components/BarChart/WalletChart.tsx
Moves the wallet graph numbers down a line so they don't overlap with the timeline selector
closes #836
=> fix wallet graph number alignment

src/makers/linxdot/hotspots.ts
The icon property got duplicated, probably a merge error. Not sure how it built on the PR but its failing now so this removes the duplicate.
=> fix lint error

src/features/hotspots/settings/updateHotspot/UpdateHotspotConfig.tsx
The fee for free asserts on the confirm page when updating a hotspot was showing 1,055,000 DC when it should show 0 DC
=> fix fee display for free assert when updating hotspot

src/features/hotspots/setup/HotspotTxnsProgressScreen.tsx
When the qr/web onboarding flow is chosen a transaction constantly fails with the bad_owner_signature reason. 
There are two steps missing comparing to the bluetooth onboarding flow:
- the transaction should be signed by the owner
- the transaction should be signed by stacking server
This PR adds these two steps
=> Sigh add_gateway transaction when qr/web onboarding is chosen

src/features/hotspots/settings/updateHotspot/UpdateHotspotConfig.tsx
Closes #890
@cokes518 I had the ability to update antenna details removed for data-only hotspots. This PR will bring that capability back. Just want to be sure this is what we want.
=> Allow data only hotspots to update antenna details.

ios/Podfile.lock
Pod lockfile needed updates after the sentry upgrade to 2.6.2
=> fix pod lockfile

src/components/HeliumActionSheet.tsx
Needed to let the sheet render before setting the data to enable scrolling on the flatlist.
=> Fix incomplete antenna list when onboarding.

ios/Helium.xcodeproj/project.pbxproj, src/features/hotspots/root/HotspotsTicker.tsx, src/features/onboarding/welcome/WelcomeScreen.tsx
This change allows the app to run fullscreen on iPad instead of a scaled down window.
Before:
after:
I quickly checked other screns in the app and they looked fine.
=> Make iPad build fullscreen

src/features/hotspots/settings/HotspotSettings.tsx, src/store/account/accountSlice.ts
- resolves issues with un-hiding your last hidden hotspot
- adds support to hide more than 5 hotspots
We now store hotspots as json instead of a comma separated list
=> Hide hotspot fixes

src/features/hotspots/setup/HotspotTxnsProgressScreen.tsx
closes #911 
instead of showing a specific js error message, show a generic retry message.
=> dont show specific onboarding error strings

ios/Helium/Info.plist
force ipad to fullscreen mode, if we want to support multitask mode for iPad we need to support all screen orientations.
=> fix iOS build

android/app/build.gradle
force androidx.work:work-runtime to 2.6.0, it was updating to a beta version requiring SDK 31 which we don't support yet.
=> fix android build

src/components/HotspotListItem.tsx, src/constants/articles.ts, src/features/hotspots/details/HexBadge.tsx, src/features/hotspots/details/HotspotDetails.tsx
This PR provides the equivalent of [this PR to the Explorer](https://github.com/helium/explorer/pull/691).
It simply swaps the original  "Read more" link to the static Helium documentation with a dynamic link which provides an in-depth overview of a hotspot's status related to reward scaling (HIP15 + HIP17) which also guides the users towards optimization of the network through collaboration with the rest of the community. An example of this page can be seen [here](https://app.hotspotty.net/hotspots/11Mo1yNoH5pX5uXM7qymvA3c626BWhjCCyJvif2QGWkjocY3AGo/rewards).
The UI/UX of this "Read more" button can be seen below:
https://user-images.githubusercontent.com/3253186/132888472-ea0dffde-7da0-4b1b-96b3-e3cd26640495.mp4
=> Link to hotspotty's in depth reward scale documentation/simulation

.editorconfig, .gitattributes
A fresh clone of this repo shows the file `gradlew.bat` as modified:
```
$ git clone https://github.com/helium/hotspot-app.git && cd hotspot-app/
// ...
$ git status
On branch main
Your branch is up to date with 'origin/main'.
Changes not staged for commit:
(use "git add <file>..." to update what will be committed)
(use "git restore <file>..." to discard changes in working directory)
modified:   android/gradlew.bat
```
The reason is a configuration which will convert line endings when the file is placed in the working directory. This conversion in unnecessary, as the file `gradlew.bat` is generated by Gradle's [`wrapper`](https://docs.gradle.org/current/userguide/gradle_wrapper.html) task with the correct line endings. It should not be modified manually. This has already been fixed on …
=> Avoid line endings conversion of gradlew.bat

src/features/wallet/root/WalletView.tsx
Fix white flash when changing currency type on settings and switching back to wallet tab.
=> Fix white flash

src/utils/polyfill.js
There are some new warning logs coming from react native for an EventEmitter deprecated call. Many libraries use this call so it gets a bunch of deprecation warning logs.
For this reason I disabled logs in release builds, and we can update they libraries causing the logs when they have a fix.
=> disable console for release builds

.eslintrc.json, ios/Podfile.lock, src/components/FollowButton.tsx, src/components/Map.tsx, src/features/hotspots/details/HotspotDetails.tsx, src/features/hotspots/root/HotspotSheetHandle.tsx, src/features/hotspots/root/HotspotsView.tsx, src/store/activity/activitySlice.ts, src/store/discovery/discoverySlice.ts, src/utils/hotspotUtils.ts
Changes the hex selection interaction to happen instantly and no longer wait for the `/hotspots/hex/id` call to finish. Because of this I added a loading state to the card itself. I also made it so that while a hex is loading you cant tap to load another, because when things are slow they all pile up and then sporadically load all at once.
closes #1045
=> add loading ui for hex selection

src/makers/controllino/hotspots.ts
Due to Bluetooth being a bit picky sometimes, we'd like to add QR code onboarding as an additional onboarding option.
=> Add QR onboarding and update help text

src/features/hotspots/settings/HotspotDiagnosticsConnection.tsx, src/features/hotspots/settings/HotspotSettings.tsx, src/features/hotspots/settings/updateHotspot/UpdateHotspotConfig.tsx, src/utils/useHotspot.ts
We are checking for existing pending transactions when tapping the update hotspot item in hotspot settings which is taking a long time to complete now that the API is slow. 
I moved the check to happen when you actually try to submit the transaction instead. Allowing more time for a current pending to clear and also flows better with the UI.
closes #1093
=> fix lag when pressing update hotspot button

android/app/src/main/AndroidManifest.xml, src/utils/appDataClient.ts
- Makes rewards charts in the app use UTC day
- Fixes Linking.openURL on Android (https://stackoverflow.com/questions/64699801/linking-canopenurl-returning-false-when-targeting-android-30-sdk-on-react-native)
=> rewards chart and android open link fixes

src/features/hotspots/setup/HotspotSetupExternalScreen.tsx, src/features/wallet/scan/ScanView.tsx
- fix camera resolution to 4:3 on Android (it doesnt support dynamic ratios like iOS does)
- revert camera2 change (looks like it was causing an intermittent new crash in expo camera on some Android devices)
=> fix android QR scan camera aspect ratio

src/features/hotspots/details/HotspotDetails.tsx, src/features/hotspots/root/HotspotsView.tsx
Caching was causing the `onFailure` call to trigger when it shouldn't. Fortunately, that call is no longer needed, it was put there to handle bad app links, but that is handled elsewhere.
=> Fix hotspot not showing when selecting from list or shortcut nav.

src/features/moreTab/more/MoreScreen.tsx, src/features/onboarding/accountImport/PassphraseAutocomplete.tsx, src/locales/en.ts, src/store/account/accountSlice.ts, src/utils/animateTransition.ts
- Adds a disable animations setting which disables all transition animations (native animations still running)
- fixes account import keyboard overlap on small devices
=> Disable animations setting

patches/react-native+0.66.1.patch
- fix keyboard avoiding view collapsing to 0 height with reduced motion settings enabled
This is a KeyboardAvoidingView React Native bug https://github.com/facebook/react-native/issues/29974
=> fix keyboard avoiding view reduced motion settings

src/utils/transactions.ts
Users are reporting that txns are being created with 0 fees. This should ensure that if for some reason the txn chain vars don't get configured on app launch, we set them when creating a new transaction.
=> config txn chain vars before creating transactions
